remote_theme: kosatyi/sjt

navigation: false
projects: true

baseurl: /blogger-php

brand: datamodel
title: DataModel
description: PHP data access and serving class

author:
  name: Stepan Kosatyi
  url: https://kosatyi.com/