remote_theme: kosatyi/sjt

navigation: false
projects: true

baseurl: /blogger-php

brand: datamodel
title: DataModel
description: PHP data access and serving class
analytics: UA-37629144-1
adsense: ca-pub-3650650669153101

author:
  name: Stepan Kosatyi
  url: https://kosatyi.com/