plugins:
  - jekyll-seo-tag

port: 4001

styles:

remote_theme: kosatyi/sjt

exclude:
  - vendor
  - src

javascript:

baseurl: /datamodel

navigation: false

projects: true

brand: datamodel
title: DataModel
description: PHP data access and serving class
analytics: UA-37629144-1

author:
  name: Stepan Kosatyi
  url: http://www.kosatyi.com/

toolbar:
