plugins:
  - jekyll-seo-tag

port: 4001

styles:

remote_theme: kosatyi/sjt

exclude:
  - vendor

javascript:

baseurl: /datamodel

navigation: false

projects: true

title: DataModel
description: PHP data access and serving class

author:
  name: Stepan Kosatyi
  url: http://www.kosatyi.com/

toolbar:
